service: conduit-backend

package:
  individually: true

provider:
  name: aws
  lambdaHashingVersion: 20201221
  region: eu-west-1

  environment:
    TABLE_NAME: ${self:custom.tableName}
custom:
  tableName: notes-go

functions:
  findAll:
    runtime: go1.x
    handler: findAll
    events:
      - http:
          path: notes
          method: GET
    package:
      artifact: bin/findAll.zip
